<?php
/**
 * Messages file for phlyMail, handler contacts
 * en (English)
 * @copyright 2002-2011 phlyLabs, Berlin (http://phlylabs.de)
 * @author Matthias Sommerfeld <mso@phlylabs.de>
 */
$WP_msg['MainFoldername'] = 'Contacts';
$WP_msg['GroupManager'] = 'Groups manager';
$WP_msg['AboutGrps'] = 'These groups are currently defined:';
$WP_msg['adbAdd'] = 'Add to Address Book';
$WP_msg['adbEntries'] = 'The Address Book contains $1 entries';
$WP_msg['adbOrga'] = 'Manage Address Book';
$WP_msg['adbSel'] = 'Add from Address Book';
$WP_msg['NewContact'] = 'New Contact';
$WP_msg['addEntry'] = 'Add entry';
$WP_msg['address'] = 'Address';
$WP_msg['address2'] = 'Address 2';
$WP_msg['addGrp'] = 'Add group';
$WP_msg['adrbContent'] = 'Contents of your Address Book:';
$WP_msg['Bcc'] = 'BCC';
$WP_msg['bday'] = 'Date of Birth';
$WP_msg['bday_format'] = '(Day / Month / Year)';
$WP_msg['date_formatstring'] = '%y-%m-%d';
$WP_msg['Cc'] = 'CC';
$WP_msg['cell'] = 'Cellphone';
$WP_msg['cmnt'] = 'Comments';
$WP_msg['cntry'] = 'Country';
$WP_msg['company'] = 'Company';
$WP_msg['LegDetails'] = 'Contact details';
$WP_msg['AskDelAdr'] = 'Do you really want to delete this contact?';
$WP_msg['AskDelAdrs'] = 'Do you really want to delete these contacts?';
$WP_msg['DelAdr'] = 'Delete contact';
$WP_msg['DelGrp'] = 'Do you really want to delete this group?';
$WP_msg['NewGrpName'] = 'Name of the new Group';
$WP_msg['NewNameGrp'] = 'New Name of the Group';
$WP_msg['dele'] = 'Delete';
$WP_msg['edit'] = 'Edit';
$WP_msg['emai1'] = 'Email';
$WP_msg['emai2'] = 'Email 2';
$WP_msg['ELenGrpName'] = 'Group names should be between 1 and 32 characters long';
$WP_msg['EGrpNameExists'] = 'This group name does already exist';
$WP_msg['fax'] = 'Fax';
$WP_msg['fnam'] = 'First Name';
$WP_msg['fon2'] = 'Private Phone';
$WP_msg['fon'] = 'Business Phone';
$WP_msg['Phone'] = 'Phone';
$WP_msg['group'] = 'Group';
$WP_msg['GrpMemb'] = 'Member of Group: <b>$1</b>';
$WP_msg['HAdr'] = 'Addresses';
$WP_msg['HGrp'] = 'Groups';
$WP_msg['HLst'] = 'Lists';
$WP_msg['Insert'] = 'Add';
$WP_msg['loc'] = 'Location';
$WP_msg['name'] = 'Name';
$WP_msg['nick'] = 'Nickname';
$WP_msg['no'] = 'No';
$WP_msg['none'] = 'none';
$WP_msg['plsSel'] = 'Please select';
$WP_msg['Receiver'] = 'Receiver';
$WP_msg['save'] = 'Save';
$WP_msg['snam'] = 'Surname';
$WP_msg['To'] = 'To';
$WP_msg['toOver'] = 'Back to Overview';
$WP_msg['unkExpFrmt'] = 'Unbknown Export Format';
$WP_msg['unkImpFrmt'] = 'Unbknown Import Format';
$WP_msg['unnamed'] = 'Unnamed';
$WP_msg['www'] = 'WWW';
$WP_msg['yes'] = 'Yes';
$WP_msg['org_bday_head'] = 'Birthdays in the next $1 days:';
$WP_msg['arr_months'] = array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
$WP_msg['arr_wdays_s'] = array('S', 'M', 'T', 'W', 'T', 'F', 'S');
$WP_msg['firstday'] = 0;
$WP_msg['AboutImport'] = 'Please select the format and local file <strong>or remote URL</strong> from the menu below. Imported addresses are always added to your current address book. If you don\'t like that, select the checkbox besides "delete" to empty the selected address book (or all contacts, if "none" is selected) before performing the import.';
$WP_msg['AboutExport'] = 'Please select the format you wish to export your current address book to. Select a specific address book or "none" for all contacts.';
$WP_msg['ImpNum'] = '$1 entries have been added to your address book.';
$WP_msg['Import'] = 'Import';
$WP_msg['Export'] = 'Export';
$WP_msg['format'] = 'Format';
$WP_msg['filename'] = 'Filename';
$WP_msg['csvMenuOption'] = 'Comma separated values (CSV)';
$WP_msg['LegendCSV'] = 'For CSV only';
$WP_msg['csvFirstLine'] = 'The first line contains the field names';
$WP_msg['csvIsQuoted'] = 'Fields are enclosed by "';
$WP_msg['csvFieldDelimiter'] = 'Field delimiter';
$WP_msg['csvImAboutSelection'] = 'Here you see the recognized fields from the CSV file just uploaded by you. Please select matching fields from this list and the list of fields from the Address Book database one by one and click on "Select".';
$WP_msg['csvImLegendSource'] = 'Source fields';
$WP_msg['select'] = 'Select';
$WP_msg['csvImLegendSelection'] = 'Your selection';
$WP_msg['csvImFromCSV'] = 'Field in CSV';
$WP_msg['csvImInDB'] = 'Field in the DB';
$WP_msg['csvExAboutSelection'] = 'Now select the order, in which the fields from he DB should be exported. Empty fields can be added by clicking "$1".';
$WP_msg['csvExInCSV'] = 'Fields in CSV';
$WP_msg['csvExFromDB'] = 'Fields in the DB';
$WP_msg['csvExSpace'] = 'Empty field';
$WP_msg['csvExAddSpace'] = 'Add empty field';
$WP_msg['SortByThis'] = 'Sort by this field';
$WP_msg['entry'] = 'entry';
$WP_msg['entries'] = 'entries';
$WP_msg['APIdesc1'] = 'Please select your desired contact(s) below. By clicking on the icon';
$WP_msg['APIdesc2'] = 'the relevant contact is selected immediately.';
$WP_msg['APIonlyGroup'] = 'Show only contacts from this group';
$WP_msg['APInone'] = 'You do not have any contacts defined.';
$WP_msg['postalddr'] = 'Postal address';
$WP_msg['postalddr_priv'] = 'Postal address (private)';
$WP_msg['postalddr_busi'] = 'Postal address (business)';
$WP_msg['address'] = 'Address';
$WP_msg['street'] = 'Street';
$WP_msg['zip'] = 'ZIP';
$WP_msg['location'] = 'Location';
$WP_msg['state'] = 'State';
$WP_msg['country'] = 'Country';
$WP_msg['General'] = 'General';
$WP_msg['PersonalContact'] = 'Personal Contact';
$WP_msg['GlobalContact'] = 'Global Contact';
$WP_msg['comp_dep'] = 'Department';
$WP_msg['comp_address'] = 'Company Address 1';
$WP_msg['comp_address2'] = 'Company Address 2';
$WP_msg['comp_street'] = 'Company Street';
$WP_msg['comp_zip'] = 'Company ZIP';
$WP_msg['comp_location'] = 'Company Location';
$WP_msg['comp_region'] = 'Company Region';
$WP_msg['comp_country'] = 'Company Country';
$WP_msg['LegendImage'] = 'Contact\'s Image';
$WP_msg['ImgUpload'] = 'Upload image (GIF / JPEG / PNG)';
$WP_msg['ImgDelImage'] = 'Delete image';
$WP_msg['ImgErrWrongType'] = 'Image is of a wrong type (GIF, JPEG, PNG)';
$WP_msg['ImgErrTooLarge'] = 'This image is too large';
// 3.04.00
$WP_msg['ENoEmptyRecord'] = 'Please enter personal data for this contact';
// 3.05.00
$WP_msg['ConfigQuotaNumberContacts'] = 'max. number of personal contacts (0 = unlimited)';
$WP_msg['ConfigQuotaNumberGroups'] = 'max. number of personal groups (0 = unlimited)';
$WP_msg['QuotaNumberContacts'] = 'number of personal contacts';
$WP_msg['QuotaNumberGroups'] = 'number of personal groups';
$WP_msg['PublicContact'] = 'Publicly visible contact';
$WP_msg['VisibilityTag'] = 'Visiblility';
$WP_msg['VisibilityPrivate'] = 'Private';
$WP_msg['VisibilityPublic'] = 'Publicly visible';
$WP_msg['VisibilityMakePublic'] = 'Publicly visible';
$WP_msg['VisibilityMakePrivate'] = 'Visible to me only';
// 3.06.50
$WP_msg['AllContacts'] = 'All Contacts';
$WP_msg['MyContacts'] = 'My Contacts';
$WP_msg['SharedContacts'] = 'Shared Contacts';
$WP_msg['PermSeeContacts'] = 'See Contacts';
$WP_msg['PermAddContact'] = 'Add Contact';
$WP_msg['PermUpdateContact'] = 'Edit Contact';
$WP_msg['PermDeleteContact'] = 'Delete Contact';
$WP_msg['PermImportContacts'] = 'Import Contacts';
$WP_msg['PermExportContacts'] = 'Export Contacts';
$WP_msg['PermAddGroup'] = 'Add Address Book';
$WP_msg['PermEditGroup'] = 'Edit Address Book';
$WP_msg['PermDeleteGroup'] = 'Delete Address Book';
$WP_msg['PermSeeGlobalContacts'] = 'See Global Contacts';
$WP_msg['PermSeeUserContacts'] = 'See User Contacts';
$WP_msg['PermMakeContactGlobal'] = 'Make Contact Global';
$WP_msg['Personal'] = 'Personal';
$WP_msg['Business'] = 'Business';
// 3.07.12
$WP_msg['ThirdNames'] = 'Add. Names';
$WP_msg['Title'] = 'Title';
$WP_msg['Role'] = 'Position';
// 3.09.70
$WP_msg['MenuOwnVCF'] = 'Own vCard';
$WP_msg['ShowInRoot'] = 'Show in "My Contacts"';
// 4.00.10
$WP_msg['CustomerNumber'] = 'Customer no.';
// 4.01.00
$WP_msg ['APILegend'] = 'External Access (LDIF)';
$WP_msg['APIAbout'] = 'You can remotely access this address book with every programme, which can handle LDIF files.<br />Copy the link below and enter it in the external programme. Use the same credentials as for your phlyMail login.';
// 4.01.07
$WP_msg['ImpTruncate'] = 'Empty address book before import';
