<?php
/**
 * Messages file for phlyMail 4, handler contacts
 * fr (French)
 * @copyright 2002-2010 phlyLabs, Berlin (http://phlylabs.de)
 * @author Nicolas Schmerber
 */
$WP_msg['MainFoldername'] = 'Contacts';
$WP_msg['GroupManager'] = 'Gestionnaire de groupes';
$WP_msg['AboutGrps'] = 'Les groupes suivants sont actuellement définis:';
$WP_msg['adbAdd'] = 'Ajouter au carnet d\`adresses';
$WP_msg['adbEntries'] = 'Le carnet d\`adresses contient $1 entrées';
$WP_msg['adbOrga'] = 'Organiser le carnet d\`adresses';
$WP_msg['adbSel'] = 'Ajouter à partir du carnet d\`adresses';
$WP_msg['NewContact'] = 'Nouveau contact';
$WP_msg['addEntry'] = 'Ajouter une entrée';
$WP_msg['address'] = 'Adresse';
$WP_msg['address2'] = 'Adresse 2';
$WP_msg['addGrp'] = 'Ajouter un groupe';
$WP_msg['adrbContent'] = 'Contenu du carnet d\`adresses:';
$WP_msg['Bcc'] = 'CCI';
$WP_msg['bday'] = 'Date de naissance';
$WP_msg['bday_format'] = '(Jour / Mois / Années)';
$WP_msg['date_formatstring'] = '%d-%m-%y';
$WP_msg['Cc'] = 'CC';
$WP_msg['cell'] = 'Mobile';
$WP_msg['cmnt'] = 'Commentaires';
$WP_msg['cntry'] = 'France';
$WP_msg['company'] = 'Entreprise';
$WP_msg['LegDetails'] = 'Détails du contact';
$WP_msg['AskDelAdr'] = 'Voulez vous vraiment supprimer ce contact?';
$WP_msg['AskDelAdrs'] = 'Voulez vous vraiment supprimer ces contacts?';
$WP_msg['DelAdr'] = 'Supprimer contact';
$WP_msg['DelGrp'] = 'Voulez vous vraiment supprimer ce groupe?';
$WP_msg['NewGrpName'] = 'Nom du nouveau groupe';
$WP_msg['NewNameGrp'] = 'Nouveau nom du groupe';
$WP_msg['dele'] = 'Supprimer';
$WP_msg['edit'] = 'Editer';
$WP_msg['emai1'] = 'Email';
$WP_msg['emai2'] = 'Email 2';
$WP_msg['ELenGrpName'] = 'Le nom des groupes doit comprendre entre 1 et 32 caractères';
$WP_msg['EGrpNameExists'] = 'Ce nom de groupe existe déjà';
$WP_msg['fax'] = 'Fax';
$WP_msg['fnam'] = 'Prénom';
$WP_msg['fon2'] = 'Téléphone privé';
$WP_msg['fon'] = 'Téléphone bureau';
$WP_msg['Phone'] = 'Téléphone';
$WP_msg['group'] = 'Groupe';
$WP_msg['GrpMemb'] = 'Membre du groupe: <b>$1</b>';
$WP_msg['HAdr'] = 'Adresses';
$WP_msg['HGrp'] = 'Groupes';
$WP_msg['HLst'] = 'Listes';
$WP_msg['Insert'] = 'Ajouter';
$WP_msg['loc'] = 'Lieu';
$WP_msg['name'] = 'Nom';
$WP_msg['nick'] = 'Surnom';
$WP_msg['no'] = 'Non';
$WP_msg['none'] = 'aucun';
$WP_msg['plsSel'] = 'Sélectionner';
$WP_msg['Receiver'] = 'Destinataire';
$WP_msg['save'] = 'Sauvegarder';
$WP_msg['snam'] = 'Nom';
$WP_msg['To'] = 'A';
$WP_msg['toOver'] = 'Retour';
$WP_msg['unkExpFrmt'] = 'Format d\`export inconnu';
$WP_msg['unkImpFrmt'] = 'Format d\`import inconnu';
$WP_msg['unnamed'] = 'Sans-nom';
$WP_msg['www'] = 'WWW';
$WP_msg['yes'] = 'Oui';
$WP_msg['org_bday_head'] = 'Anniversaires dans les $1 prochains jours:';
$WP_msg['arr_months'] = array('Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Decembre');
$WP_msg['arr_wdays_s'] = array('D', 'L', 'M', 'M', 'J', 'W', 'S');
$WP_msg['firstday'] = 0;
$WP_msg['AboutImport'] = 'Merci de sélectionner le format et le fichier local <strong>ou distant</strong> à partir du menu ci-dessous. Ici les adresses importées sont toujours ajoutées à votre carnet d\'adresses en cours. Si vous le souhaitez, cochez "effacer" (ou tous les contacts si aucun n\'est sélectionné) pour vider le carnet d\'adresses avant son importation.';
$WP_msg['AboutExport'] = 'Merci de sélectionner le format choisi pour exporter votre carnet d\'adresses en cours. Sélectionner un carnet d\'adresses spécifiques ou "aucun" pour tous les contacts.';
$WP_msg['ImpNum'] = '$1 entrées ont été ajoutées à votre carnet d\`adresses.';
$WP_msg['Import'] = 'Importer';
$WP_msg['Export'] = 'Exporter';
$WP_msg['format'] = 'Format';
$WP_msg['filename'] = 'Nom du fichier';
$WP_msg['csvMenuOption'] = 'Liste séparée par des virgules (CSV)';
$WP_msg['LegendCSV'] = 'Pour format CSV uniquement';
$WP_msg['csvFirstLine'] = 'La première ligne contient les noms des champs';
$WP_msg['csvIsQuoted'] = 'Les champs sont délimités par "';
$WP_msg['csvFieldDelimiter'] = 'Délimiteur de champs';
$WP_msg['csvImAboutSelection'] = 'Voici les champs reconnu à partir du fichier qui vient d\`être chargé. Choisir les champs correspondants dans la liste et les champs correspondant dans le carnet d\`adresses un à un, puis cliquer sur "Séléctionner".';
$WP_msg['csvImLegendSource'] = 'Champs sources';
$WP_msg['select'] = 'Sélectionner';
$WP_msg['csvImLegendSelection'] = 'Votre sélection';
$WP_msg['csvImFromCSV'] = 'Champ dans le CSV';
$WP_msg['csvImInDB'] = 'Champ dans la base';
$WP_msg['csvExAboutSelection'] = 'Choisir l\`ordre dans lequel les champs du carnet d\adresses doivent être exporté. Des champs vides peuvent être rajoutés en cliquant sur "$1".';
$WP_msg['csvExInCSV'] = 'Champs dans le CSV';
$WP_msg['csvExFromDB'] = 'Champs dans le carnet d\`adresses';
$WP_msg['csvExSpace'] = 'Champ vide';
$WP_msg['csvExAddSpace'] = 'Ajouter un champ vide';
$WP_msg['SortByThis'] = 'Trier par champ';
$WP_msg['entry'] = 'entrée';
$WP_msg['entries'] = 'entrées';
$WP_msg['APIdesc1'] = 'Sélectionner le(s) contact(s) désiré(s) ci-dessous en cliquant sur le(s) icône(s).';
$WP_msg['APIdesc2'] = 'le contact est sélectionné immédiatement.';
$WP_msg['APIonlyGroup'] = 'Afficher seulement les contacts de ce groupe';
$WP_msg['APInone'] = 'Aucun contact défini.';
$WP_msg['postalddr'] = 'Adresse postale';
$WP_msg['postalddr_priv'] = 'Adresse postale (privée)';
$WP_msg['postalddr_busi'] = 'Adresse postale (bureau)';
$WP_msg['address'] = 'Adresse';
$WP_msg['street'] = 'Rue';
$WP_msg['zip'] = 'Code postal';
$WP_msg['location'] = 'Lieu';
$WP_msg['state'] = 'Département';
$WP_msg['country'] = 'Pays';
$WP_msg['General'] = 'Général';
$WP_msg['PersonalContact'] = 'Contact personnel';
$WP_msg['GlobalContact'] = 'Contact global';
$WP_msg['comp_dep'] = 'Département';
$WP_msg['comp_address'] = 'Adresse entreprise ';
$WP_msg['comp_address2'] = 'Adresse entreprise 2';
$WP_msg['comp_street'] = 'Rue entreprise';
$WP_msg['comp_zip'] = 'Code postal entreprise';
$WP_msg['comp_location'] = 'Lieu entreprise';
$WP_msg['comp_region'] = 'Région entreprise';
$WP_msg['comp_country'] = 'Pays entreprise';
$WP_msg['LegendImage'] = 'Image du contact';
$WP_msg['ImgUpload'] = 'Déposer une image (GIF / JPEG / PNG)';
$WP_msg['ImgDelImage'] = 'Supprimer image';
$WP_msg['ImgErrWrongType'] = 'Image au mauvais format (GIF, JPEG, PNG)';
$WP_msg['ImgErrTooLarge'] = 'Une image doit être de taille max. $1';
// 3.04.00
$WP_msg['ENoEmptyRecord'] = 'Entrer des données personnelles pour ce contact';
// 3.05.00
$WP_msg['ConfigQuotaNumberContacts'] = 'Nombre max. de contacts personnels (0 = illimité)';
$WP_msg['ConfigQuotaNumberGroups'] = 'Nombre max. de groupes personnels (0 = illimité)';
$WP_msg['QuotaNumberContacts'] = 'Nombre de contacts personnels';
$WP_msg['QuotaNumberGroups'] = 'Nombre de groupes personnels';
$WP_msg['PublicContact'] = 'Contact visible par tous';
$WP_msg['VisibilityTag'] = 'Visibilité';
$WP_msg['VisibilityPrivate'] = 'Privé';
$WP_msg['VisibilityPublic'] = 'Visible par tous';
$WP_msg['VisibilityMakePublic'] = 'Visible par tous';
$WP_msg['VisibilityMakePrivate'] = 'Visible par moi uniquement';
// 3.06.50
$WP_msg['AllContacts'] = 'Tous les contacts';
$WP_msg['MyContacts'] = 'Mes contacts';
$WP_msg['SharedContacts'] = 'Contacts partagés';
$WP_msg['PermSeeContacts'] = 'Voir les contacts';
$WP_msg['PermAddContact'] = 'Ajouter contact';
$WP_msg['PermUpdateContact'] = 'Editer contact';
$WP_msg['PermDeleteContact'] = 'Supprimer contact';
$WP_msg['PermImportContacts'] = 'Importer contacts';
$WP_msg['PermExportContacts'] = 'Exporter contacts';
$WP_msg['PermAddGroup'] = 'Ajouter un carnet d\`adresses';
$WP_msg['PermEditGroup'] = 'Editer le carnet d\`adresses';
$WP_msg['PermDeleteGroup'] = 'Supprimer le carnet d\`adresses';
$WP_msg['PermSeeGlobalContacts'] = 'Voir les contacts globaux';
$WP_msg['PermSeeUserContacts'] = 'Voir les contacts utilisateur';
$WP_msg['PermMakeContactGlobal'] = 'Rendre le contact global';
// 3.07.12
$WP_msg['ThirdNames'] = 'Noms add.';
$WP_msg['Title'] = 'Titre';
$WP_msg['Role'] = 'Position';
// 3.09.70
$WP_msg['MenuOwnVCF'] = 'Possède une vCard';
$WP_msg['ShowInRoot'] = 'Afficher dans "Mes Contacts"';
// 4.00.10
$WP_msg['CustomerNumber'] = 'Client no.';
// 4.01.00
$WP_msg ['APILegend'] = 'Accès Externe (LDIF)';
$WP_msg['APIAbout'] = 'Vous pouvez accèder à ce calendrier de l\`extérieur avec n\`importe quel programme supportant le protocole LDIF.<br />Copier le lien suivant et l\'importer dans le programme externe. Utiliser les mêmes identifiants que votre compte phlyMail.';
// 4.01.07
$WP_msg['ImpTruncate'] = 'Vider le carnet d\'adresses avant de l\'importer';
