<?php
/**
 * Messages file for phlyMail 3.7+, handler bookmarks
 * de (German)
 * (c) 2002-2011 phlyLabs, Berlin (http://phlylabs.de)
 */
$WP_msg['MainFoldername'] = 'Lesezeichen';
$WP_msg['GroupManager'] = 'Ordnerverwaltung';
$WP_msg['AboutGrps'] = 'Diese Ordner sind zurzeit definiert:';
$WP_msg['addEntry'] = 'Eintrag hinzufügen';
$WP_msg['addGrp'] = 'Neuer Ordner';
$WP_msg['NewBookmark'] = 'Neues Lesezeichen';
$WP_msg['AskDelAdr'] = 'Soll dieses Lesezeichen wirklich gelöscht werden?';
$WP_msg['AskDelAdrs'] = 'Sollen die gewählten Lesezeichen wirklich gelöscht werden?';
$WP_msg['DelAdr'] = 'Lesezeichen löschen';
$WP_msg['DelGrp'] = 'Soll der Ordner wirklich gelöscht werden?';
$WP_msg['NewGrpName'] = 'Name des neuen Ordners';
$WP_msg['NewNameGrp'] = 'Neuer Name des Ordners';
$WP_msg['dele'] = 'Löschen';
$WP_msg['edit'] = 'Editieren';
$WP_msg['emai1'] = 'Email';
$WP_msg['emai2'] = 'Email 2';
$WP_msg['ELenGrpName'] = 'Ordnernamen sollten zwischen 1 und 32 Zeichen lang sein';
$WP_msg['EGrpNameExists'] = 'Dieser Ordnername ist bereits vergeben';
$WP_msg['group'] = 'Ordner';
$WP_msg['GrpMemb'] = 'Gehört zu Ordner: <b>$1</b>';
$WP_msg['HAdr'] = 'Lesezeichen';
$WP_msg['HGrp'] = 'Ordner';
$WP_msg['HLst'] = 'Verteiler';
$WP_msg['Insert'] = 'Einfügen';
$WP_msg['name'] = 'Name';
$WP_msg['no'] = 'Nein';
$WP_msg['plsSel'] = 'Bitte auswählen';
$WP_msg['toOver'] = 'Zur Übersicht';
$WP_msg['unkExpFrmt'] = 'Unbekanntes Exportformat';
$WP_msg['unkImpFrmt'] = 'Unbekanntes Importformat';
$WP_msg['unnamed'] = 'Unbenannt';
$WP_msg['yes'] = 'Ja';
$WP_msg['AboutImport'] = 'Sie können hier Lesezeichen aus anderen Programmen in phlyMail importieren. Wählen Sie dazu das Format und die lokale Datei aus dem Menü aus. Importierte Lesezeichen werden immer Ihrem aktuellen Bestand zugefügt.';
$WP_msg['AboutExport'] = 'Wählen Sie hier das Format, in welchem Sie Ihre Lesezeichen exportieren möchten.';
$WP_msg['ImpNum'] = 'Es wurden $1 Einträge zugefügt';
$WP_msg['Import'] = 'Importieren';
$WP_msg['Export'] = 'Exportieren';
$WP_msg['format'] = 'Format';
$WP_msg['filename'] = 'Dateiname';
$WP_msg['select'] = 'Auswählen';
$WP_msg['SortByThis'] = 'Nach diesem Feld sortieren';
$WP_msg['entry'] = 'Eintrag';
$WP_msg['entries'] = 'Einträge';
$WP_msg['PersonalBookmark'] = 'Persönliches Lesezeichen';
$WP_msg['GlobalBookmark'] = 'Globales Lesezeichen';
$WP_msg['ConfigQuotaNumberBookmarks'] = 'max. Anzahl persönlicher Lesezeichen (0 = unbegrenzt)';
$WP_msg['ConfigQuotaNumberGroups'] = 'max. Anzahl persönlicher Ordner (0 = unbegrenzt)';
$WP_msg['QuotaNumberBookmarks'] = 'Anzahl persönlicher Lesezeichen';
$WP_msg['QuotaNumberGroups'] = 'Anzahl persönlicher Ordner';
$WP_msg['PublicBookmark'] = 'Öffentliches Lesezeichen';
$WP_msg['PublicBookmarks'] = 'Öffentliche Lesezeichen';
$WP_msg['VisibilityTag'] = 'Sichtbarkeit';
$WP_msg['VisibilityPrivate'] = 'Privat';
$WP_msg['VisibilityPublic'] = 'Öffentlich sichtbar';
$WP_msg['VisibilityMakePublic'] = 'Für andere sichtbar';
$WP_msg['VisibilityMakePrivate'] = 'Nur für mich sichtbar';
$WP_msg['AllBookmarks'] = 'Alle Lesezeichen';
$WP_msg['MyBookmarks'] = 'Meine Lesezeichen';
$WP_msg['SharedBookmarks'] = 'Freigegebene Lesezeichen';
$WP_msg['PermSeeBookmarks'] = 'Lesezeichen ansehen';
$WP_msg['PermAddBookmark'] = 'Lesezeichen hinzufügen';
$WP_msg['PermUpdateBookmark'] = 'Lesezeichen bearbeiten';
$WP_msg['PermDeleteBookmark'] = 'Lesezeichen löschen';
$WP_msg['PermImportBookmarks'] = 'Lesezeichen importieren';
$WP_msg['PermExportBookmarks'] = 'Lesezeichen exportieren';
$WP_msg['PermAddGroup'] = 'Ordner hinzufügen';
$WP_msg['PermEditGroup'] = 'Ordner umbenennen';
$WP_msg['PermDeleteGroup'] = 'Ordner löschen';
$WP_msg['PermSeeGlobalBookmarks'] = 'Globale Lesezeichen sehen';
$WP_msg['PermSeeUserBookmarks'] = 'Benutzer-Lesezeichen sehen';
$WP_msg['PermMakeBookmarkGlobal'] = 'Lesezeichen global machen';
$WP_msg['BMName'] = 'Name';
$WP_msg['BMURL'] = 'URL';
$WP_msg['BMDescription'] = 'Beschreibung';
$WP_msg['BMFavouriteBookmark'] = 'Favoriten-Lesezeichen';
$WP_msg['OpenInPreview'] = 'Im Vorschaufenster öffnen';
$WP_msg['OpenInNewWindow'] = 'In neuem Fenster öffnen';
$WP_msg['FavouriteBookmarks'] = 'Favorisierte Lesezeichen';
