<?php
/**
 * Messages file for phlyMail 3.7+, handler RSS
 * de (German)
 * (c) 2002-2013 phlyLabs, Berlin (http://phlylabs.de)
 */
$WP_msg['MainFoldername'] = 'Newsfeeds';
$WP_msg['addEntry'] = 'Eintrag hinzufügen';
$WP_msg['addGrp'] = 'Neuer Ordner';
$WP_msg['RSSAddNewFeed'] = 'Neuer Feed';
$WP_msg['AskDelAdr'] = 'Soll dieser Feed wirklich gelöscht werden?';
$WP_msg['AskDelAdrs'] = 'Sollen die gewählten Feeds wirklich gelöscht werden?';
$WP_msg['DelAdr'] = 'Feed löschen';
$WP_msg['DelGrp'] = 'Soll der Ordner wirklich gelöscht werden?';
$WP_msg['NewGrpName'] = 'Name des neuen Ordners';
$WP_msg['NewNameGrp'] = 'Neuer Name des Ordners';
$WP_msg['dele'] = 'Löschen';
$WP_msg['edit'] = 'Editieren';
$WP_msg['FeedItemTitle'] = 'Titel';
$WP_msg['FeedItemAuthor'] = 'Autor';
$WP_msg['ELenGrpName'] = 'Ordnernamen sollten zwischen 1 und 32 Zeichen lang sein';
$WP_msg['EGrpNameExists'] = 'Dieser Ordnername ist bereits vergeben';
$WP_msg['group'] = 'Ordner';
$WP_msg['GrpMemb'] = 'Gehört zu Ordner: <b>$1</b>';
$WP_msg['HAdr'] = 'Feed';
$WP_msg['HGrp'] = 'Ordner';
$WP_msg['HLst'] = 'Verteiler';
$WP_msg['Insert'] = 'Einfügen';
$WP_msg['name'] = 'Name';
$WP_msg['no'] = 'Nein';
$WP_msg['plsSel'] = 'Bitte auswählen';
$WP_msg['toOver'] = 'Zur Übersicht';
$WP_msg['unkExpFrmt'] = 'Unbekanntes Exportformat';
$WP_msg['unkImpFrmt'] = 'Unbekanntes Importformat';
$WP_msg['unnamed'] = 'Unbenannt';
$WP_msg['yes'] = 'Ja';
$WP_msg['AboutImport'] = 'Sie können hier Feeds aus anderen Programmen in phlyMail importieren. Wählen Sie dazu das Format und die lokale Datei aus dem Menü aus. Importierte Feeds werden immer Ihrem aktuellen Bestand zugefügt.';
$WP_msg['AboutExport'] = 'Wählen Sie hier das Format, in welchem Sie Ihre Feeds exportieren möchten.';
$WP_msg['ImpNum'] = 'Es wurden $1 Einträge zugefügt';
$WP_msg['Import'] = 'Importieren';
$WP_msg['Export'] = 'Exportieren';
$WP_msg['format'] = 'Format';
$WP_msg['filename'] = 'Dateiname';
$WP_msg['select'] = 'Auswählen';
$WP_msg['SortByThis'] = 'Nach diesem Feld sortieren';
$WP_msg['entry'] = 'Eintrag';
$WP_msg['entries'] = 'Einträge';
$WP_msg['PersonalFeed'] = 'Persönlicher Feed';
$WP_msg['GlobalFeed'] = 'Globaler Feed';
$WP_msg['ConfigQuotaNumberFeeds'] = 'max. Anzahl persönlicher Feeds (0 = unbegrenzt)';
$WP_msg['ConfigQuotaNumberGroups'] = 'max. Anzahl persönlicher Ordner (0 = unbegrenzt)';
$WP_msg['QuotaNumberFeeds'] = 'Anzahl persönlicher Feeds';
$WP_msg['QuotaNumberGroups'] = 'Anzahl persönlicher Ordner';
$WP_msg['PublicFeed'] = 'Öffentlicher Feed';
$WP_msg['PublicFeeds'] = 'Öffentliche Feeds';
$WP_msg['VisibilityTag'] = 'Sichtbarkeit';
$WP_msg['VisibilityPrivate'] = 'Privat';
$WP_msg['VisibilityPublic'] = 'Öffentlich sichtbar';
$WP_msg['VisibilityMakePublic'] = 'Für andere sichtbar';
$WP_msg['VisibilityMakePrivate'] = 'Nur für mich sichtbar';
$WP_msg['AllFeeds'] = 'Alle Feeds';
$WP_msg['MyFeeds'] = 'Meine Feeds';
$WP_msg['SharedFeeds'] = 'Freigegebene Feeds';
$WP_msg['PermSeeFeeds'] = 'Feed ansehen';
$WP_msg['PermAddFeed'] = 'Feed hinzufügen';
$WP_msg['PermUpdateFeed'] = 'Feed bearbeiten';
$WP_msg['PermDeleteFeed'] = 'Feed löschen';
$WP_msg['PermImportFeeds'] = 'Feed importieren';
$WP_msg['PermExportFeeds'] = 'Feed exportieren';
$WP_msg['PermAddGroup'] = 'Ordner hinzufügen';
$WP_msg['PermEditGroup'] = 'Ordner umbenennen';
$WP_msg['PermDeleteGroup'] = 'Ordner löschen';
$WP_msg['PermSeeGlobalFeeds'] = 'Globale Feeds sehen';
$WP_msg['PermSeeUserFeeds'] = 'Benutzer-Feeds sehen';
$WP_msg['PermMakeFeedGlobal'] = 'Feeds global machen';
$WP_msg['BMName'] = 'Name';
$WP_msg['BMURL'] = 'URL';
$WP_msg['BMDescription'] = 'Beschreibung';
$WP_msg['BMFavouriteFeed'] = 'Favoriten-Feed';
$WP_msg['OpenInPreview'] = 'Im Vorschaufenster öffnen';
$WP_msg['OpenInNewWindow'] = 'In neuem Fenster öffnen';
$WP_msg['FavouriteFeeds'] = 'Favorisierte Feeds';
$WP_msg['RSSExchangeFeeds'] = 'Newsfeeds';
$WP_msg['RSSFeedSubscriptions'] = 'Newsfeeds';
