<?php
/**
 * Messages file for phlyMail 3.7, handler RSS
 * en (English)
 * @author Matthias Sommerfeld <mso@phlylabs.de>
 * @copyright 2002-2013 phlyLabs, Berlin (http://phlylabs.de)
 */
$WP_msg['MainFoldername'] = 'Newsfeeds';
$WP_msg['addFeed'] = 'Add feed';
$WP_msg['addGrp'] = 'New folder';
$WP_msg['RSSAddNewFeed'] = 'New feed';
$WP_msg['AskDelAdr'] = 'Do you really want to delete this feed?';
$WP_msg['AskDelAdrs'] = 'Do you really want to delete these feeds?';
$WP_msg['DelAdr'] = 'Delete feed';
$WP_msg['DelGrp'] = 'Do you really want to delete this folder?';
$WP_msg['NewGrpName'] = 'Name of the new folder';
$WP_msg['NewNameGrp'] = 'New name of the folder';
$WP_msg['dele'] = 'Delete';
$WP_msg['edit'] = 'Edit';
$WP_msg['FeedItemTitle'] = 'Title';
$WP_msg['FeedItemAuthor'] = 'Author';
$WP_msg['ELenGrpName'] = 'Folder names should have between 1 and 32 characters';
$WP_msg['EGrpNameExists'] = 'This folder name already exists';
$WP_msg['group'] = 'Folder';
$WP_msg['GrpMemb'] = 'Belongs to folder: <strong>$1</strong>';
$WP_msg['HAdr'] = 'Feed';
$WP_msg['HGrp'] = 'Folder';
$WP_msg['name'] = 'Name';
$WP_msg['no'] = 'No';
$WP_msg['yes'] = 'Yes';
$WP_msg['plsSel'] = 'Please select';
$WP_msg['toOver'] = 'To overview';
$WP_msg['unkExpFrmt'] = 'Unknown export format';
$WP_msg['unkImpFrmt'] = 'Unknown import format';
$WP_msg['AboutImport'] = 'Here you can import feeds from other programmes into phlyMail. Please select the format and the local file from the menu. Imported feeds are added to the current database.';
$WP_msg['AboutExport'] = 'Please select the format you want to export your feeds to.';
$WP_msg['ImpNum'] = '$1 entries have been added';
$WP_msg['Import'] = 'Import';
$WP_msg['Export'] = 'Export';
$WP_msg['format'] = 'Format';
$WP_msg['filename'] = 'Filename';
$WP_msg['select'] = 'Select';
$WP_msg['SortByThis'] = 'Sort by this field';
$WP_msg['entry'] = 'entry';
$WP_msg['entries'] = 'entries';
$WP_msg['PersonalFeed'] = 'Personal feed';
$WP_msg['GlobalFeed'] = 'Global feed';
$WP_msg['ConfigQuotaNumberNewsfeeds'] = 'max. number of personal feeds (0 = unlimited)';
$WP_msg['ConfigQuotaNumberGroups'] = 'max. number of personal folders (0 = unlimited)';
$WP_msg['QuotaNumberNewsfeeds'] = 'Number of personal feeds';
$WP_msg['QuotaNumberGroups'] = 'Number of personal folders';
$WP_msg['PublicFeed'] = 'Public feed';
$WP_msg['PublicNewsfeeds'] = 'Public Newsfeeds';
$WP_msg['VisibilityTag'] = 'Visibility';
$WP_msg['VisibilityPrivate'] = 'Personal';
$WP_msg['VisibilityPublic'] = 'Publicly visible';
$WP_msg['VisibilityMakePublic'] = 'Visible to others';
$WP_msg['VisibilityMakePrivate'] = 'Visible for me only';
$WP_msg['AllNewsfeeds'] = 'All Newsfeeds';
$WP_msg['MyFeeds'] = 'My Newsfeeds';
$WP_msg['SharedFeeds'] = 'Shared Feeds';
$WP_msg['PermSeeFeeds'] = 'View feeds';
$WP_msg['PermAddFeed'] = 'Add feeds';
$WP_msg['PermUpdateFeed'] = 'Edit feeds';
$WP_msg['PermDeleteFeed'] = 'Delete feeds';
$WP_msg['PermImportFeeds'] = 'Import feeds';
$WP_msg['PermExportFeeds'] = 'Export feeds';
$WP_msg['PermAddGroup'] = 'Add folders';
$WP_msg['PermEditGroup'] = 'Rename folders';
$WP_msg['PermDeleteGroup'] = 'Delete folders';
$WP_msg['PermSeeGlobalFeeds'] = 'See global feeds';
$WP_msg['PermSeeUserFeeds'] = 'See personal feeds';
$WP_msg['PermMakeFeedGlobal'] = 'Make feeds global';
$WP_msg['BMName'] = 'Name';
$WP_msg['BMURL'] = 'URL';
$WP_msg['BMDescription'] = 'Description';
$WP_msg['BMFavouriteFeed'] = 'Favourite feed';
$WP_msg['OpenInPreview'] = 'Open in preview window';
$WP_msg['OpenInNewWindow'] = 'Open in a new window';
$WP_msg['FavouriteFeeds'] = 'Favourite Feeds';
$WP_msg['RSSExchangeFeeds'] = 'Newsfeeds';
$WP_msg['RSSFeedSubscriptions'] = 'Newsfeeds';
